name=Patchugino_PT100
version=1.0.0
author=Innuvatech
maintainer=Innuvatech <andrea.rantin@Innuvatech.com>
sentence=Simple and user friendly library to use the Patchugino PT100 shield board
paragraph=For easy and immediate developement
category=Device Control
url=https://github.com/Innuvatech/Patchugino_PT100
architectures=*
includes=patchugino_pt100.h
depends=Patchugo_Core